### ISSUE TITLE
Error with .net 4.5.2

### ISSUE THREAD

**Issue by trungnd1985** [lelong37/urf#12]
Hi Mr Longle,

I used to use your framework in my project, but now when install URF.Repository framework, There is a issues with me:

Could not load file or assembly 'Urf.Repository.Pattern' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Can you help me resolve it

**Comment by tonysneed** [comment]
@trungnd1985 The Urf libraries are now available as NuGet packages: https://www.nuget.org/packages?q=Urf.  Just install from those and you'll be fine.  For example, in Visual Studio open the Package Manager Console and enter: `install-package Urf.Repository.Pattern` .  The other Urf packages will automatically bring in dependencies they need.

**Comment by reddy6ue** [comment]
Close this then?

**Comment by lelong37** [comment]
Yes, closing...
