### ISSUE TITLE
Support for EF Core

### ISSUE THREAD

**Issue by ortrails** [lelong37/URF#15]

**Comment by tonysneed** [comment]
you mean EF Core?

**Comment by ortrails** [comment]
yes.

**Comment by tonysneed** [comment]
@lelong37, Can we port the non-OData part to use TE for EF Core? We can create create a separate NuGet package for that.

**Comment by tonysneed** [comment]
@lelong37 and I discussed, and we plan to port URF to EF Core now, so when we'll be ready when OData for ASP.NET Core is released.

**Comment by lelong37** [comment]
Thanks @ortrails, it's in progress, we're also waiting for OData for ASPNet to really focus on this https://github.com/OData/WebApi/issues/939#issuecomment-332756006. Should be able to provide some rough timelines as soon as OData (alpha) is released, https://github.com/OData/WebApi/issues/939#issuecomment-332756006.
