### ISSUE TITLE
DbTransaction Not Disposed

### ISSUE THREAD

**Issue by DevBiker** [lelong37/URF#17]
Applies to 4.2.
If a transaction is started with UnitOfWork, it is not explicitly closed in the Dispose method. The _transaction field in class UnitOfWork should be checked and disposed as needed.

**Comment by lelong37** [comment]
Thanks @DevBiker, we've completely removed dispose from UnitOfWork, this is reflected in our alpha release, will review this ask with the team and get back to you on this cc: // @tonysneed

**Comment by tonysneed** [comment]
The recommended pattern here is to nest a `using` for `DbTransaction` inside a `using` for `DbContext`.  See <https://msdn.microsoft.com/en-us/library/dn456843(v=vs.113).aspx>.

As @lelong37 mentioned, you are not supposed to follow the `using` pattern when dependency injection is used, which is typical of most web applications and is the default with ASP.NET Core.  In those cases, the framework will manage the lifetime of these objects and call dispose when appropriate.  The only reason you would dispose of these directly (via `using`) is when you are using them in some other context, such as a .NET console app.
