### ISSUE TITLE
Query().SelectPage() Method Error

### ISSUE THREAD

**Issue by muratyuceer** [lelong37/URF#22]
Hi when i try to Query().SelecPage() its throw exception

System.NotSupportedException: The method 'Skip' is only supported for sorted input in LINQ to Entities. The method 'OrderBy' must be called before the method 'Skip'.

Also i thing QueryFluent and QueryObject not orm independent can you move them common project

Thank you

**Comment by lelong37** [comment]
Yes, you will need to pass in a lambda expression for sorting if your doing paging. If not, it maybe difficult to page without an definitive order to go by, in order to do paging.
