### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by celestialtek** [lelong37/URF#27]
hi mr lelong37,

Are you missing TrackableEntities.Common packages when get package from NuGet, when I got source code to build dll, I saw you use ITrackable instead of. If I get URF via Nuget, issues when run because URF missing dependency library. You can check again if I think wrong.

Thank you

**Comment by lelong37** [comment]
Thanks, will look into this tomorrow and keep you posted, labeling this as in-progress.

**Comment by lelong37** [comment]
Also wanted to point out, integrating with Trackables (e.g. ITrackable) will allow us to maintain object graphs across physical boundaries (e.g. conceptual: web -> api -> database, in practiced: Angular -> Web API -> SQL Server).

**Comment by tonysneed** [comment]
This is due to having a .nuget folder and configuring projects for package restore, which has been deprecated by NuGet.  Will fix.
- Remove .nuget folder.
- Remove `<RestorePackages>true</RestorePackages>`

**Comment by tonysneed** [comment]
If you get latest and build, the packages will now be automatically restored.

FYI, the master branch has the latest bits, which will soon be released as v5.1.0-rc and leverage Trackable Entities for tracking and persisting object state across service boundaries.

**Comment by celestialtek** [comment]
Thank for all :)
