### ISSUE TITLE
issues with DeleteAsync

### ISSUE THREAD

**Issue by celestialtek** [lelong37/URF#29]
Hi lelong37,

I showed you missing Context.ApplyChanges(entity) in method Repository.DeleteAsync

public virtual async Task<bool> DeleteAsync(CancellationToken cancellationToken, params object[] keyValues)
        {
            var entity = await FindAsync(cancellationToken, keyValues);

            if (entity == null)
            {
                return false;
            }

            entity.TrackingState = TrackingState.Deleted;
            return true;
        }

Please fix to DeleteAsync

Thank you

**Comment by lelong37** [comment]
We're on it.

**Comment by tonysneed** [comment]
I’ll add a test for this with the fix.

**Comment by celestialtek** [comment]
Thanks all
