### ISSUE TITLE
Keep getting System.BadImageFormatException when I upgraded to 4.2

### ISSUE THREAD

**Issue by reddy6ue** [lelong37/URF#34]
I upgraded the old Repository.Pattern from 3.3.4 to Urf.Repository.Pattern 4.2 and I started getting the following exception

> Could not load file or assembly 'Urf.Repository.Pattern, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
> 
> Exception thrown: 'System.BadImageFormatException' in mscorlib.dll
> An exception of type 'System.BadImageFormatException' occurred in mscorlib.dll but was not handled in user code
> Could not load file or assembly 'Urf.Repository.Pattern, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by lelong37** [comment]
@tonysneed could you please look into this?

**Comment by tonysneed** [comment]
I need to know what kind of project he is adding th package to? What flavor and version of .NET?

**Comment by tonysneed** [comment]
@lelong37  Have you been able to replicate this? BTW, I love the labels! 😄

**Comment by reddy6ue** [comment]
Sorry. I can't replicate it either. Used to happen on my old laptop. Disappeared after a visual studio update. No idea what happened.
