### ISSUE TITLE
Delete not working in sample project

### ISSUE THREAD

**Issue by briancasady** [lelong37/URF#39]
Hey guys,  

Amazing solution, really learning a lot as i go thru it.  but I cant seem to get past the delete methods in the Service.  In your sample repo, or in the live demo on azure.

Please advise.

Thanks again for sharing your expertise

--brian

**Comment by lelong37** [comment]
Hey @briancasady , deletes should be working make sure you are setting the TrackingState e.g. `https://github.com/lelong37/URF/blob/master/main/Sample/Northwind.Web/Api/CustomerController.cs`, also go ahead and clone the repo and run the integration test, which will automatically create a db NorthindTest to run them, make sure you set the connection string in Northwind.Test.
